<?php

$this->siteMap = array(
    (object) [
        'group'         => 'Dashboard',
        'label'         => 'Dashboard',
        'icon'          => 'fa-dashboard',
        'url'           => url('dashboard'),
        'class'         => '',
        'show'          => true,
        'active_by'     => 'view',
    ],
    (object)array(
        'group'         => 'Jobs_listings',
        'page'          => 'jobs_listings',
        'label'         => lang('jobs_listings_heading'),
        'icon'          => 'fa-universal-access',
        'url'           => url('jobs_listings'),
        'class'         => 'Jobs_listings',
        'show'          => true,
        'show_heading'  => false,
        'active_by'     => 'view',
    ),
    (object)array(
        'group'         => 'Agency Staff',
        'page'          => 'agency_staff',
        'label'         => 'Internal Staff',
        'icon'          => 'fa-universal-access',
        'url'           => url('agency_staff'),
        'class'         => 'Agency_Staff',
        'show'          => true,
        'show_heading'  => false,
        'active_by'     => 'view',
    ),
    (object)array(
        'group'         => 'Recruiters',
        'page'          => 'recruiters',
        'label'         => lang('recruiters_heading'),
        'icon'          => 'fa-universal-access',
        'url'           => url('recruiters'),
        'class'         => 'Recruiters',
        'show'          => true,
        'show_heading'  => false,
        'active_by'     => 'view',
    ),
    (object) [
        'group'         => 'Candidates Management',
        'page'          => 'candidates',
        'label'         => lang('candidates_heading'),
        'icon'          => 'fa-users',
        'url'           => url('candidates'),
        'class'         => '',
        'show'          => true,
        'show_heading'  => true,
        'active_by'     => 'candidates',
        'items' => array(
            (object) [
                'page'          => 'candidates',
                'view'          => 'listing',
                'label'         => lang('candidates_heading'),
                'icon'          => 'fa-user-circle',
                'url'           => url('candidates'),
                'show'          => true,
            ],
            // ADD ONBOARDING SUBMENU ITEM HERE
            (object) [
                'page'          => 'candidates_onboarding',
                'view'          => 'onboarding_listing',
                'label'         => 'Onboarding Management',
                'icon'          => 'fa-tasks',
                'url'           => url('candidates/onboarding_listing'),
                'show'          => true,
            ],
        ),
    ],
             (object) [
        'group'         => 'Notifications',
        'page'          => 'notifications',
        'label'         => lang('notifications_heading'),
        'icon'          => 'fa-bell',
        'url'           => url('notifications'),
        'class'         => '',
        'show'          => true,
        'show_heading'  => false,
        'active_by'     => 'notifications',
        'badge_count'   => true, // This will show unread count
    ],

    // Add to agency sitemap array  
(object) [
    'group'         => 'Chat',
    'page'          => 'chat',
    'label'         => lang('chat_heading'),
    'icon'          => 'fa-comments',
    'url'           => url('chat'),
    'class'         => 'Chat',
    'show'          => true,
    'show_heading'  => false,
    'active_by'     => 'chat',
    'badge_count'   => true, // This will show unread message count
],
    (object)array(
        'group' => 'Templates',
        'page' => 'templates',
        'label' => 'Templates',
        'icon' => 'fa-paint-brush',
        'url' => url('templates'),
        'class' => '',
        'show' => true,
        'active_by' => 'view',
        'items' => array(
            (object)array(
                'page' => 'templates',
                'view' => 'listing',
                'label' => 'Templates',
                'icon' => 'fa-file',
                'url' => url('templates'),
                'show' => true,
            ),
            (object)array(
                'page' => 'template_sections',
                'view' => 'listing', 
                'label' => 'Template Sections',
                'icon' => 'fa-puzzle-piece',
                'url' => url('template_sections'),
                'show' => true,
            ),
            (object)array(
                'page' => 'agency_templates',
                'view' => 'build',
                'label' => 'Template Builder',
                'icon' => 'fa-wrench',
                'url' => url('agency_templates/build'),
                'show' => true,
            ),
    
            // ADD TEST FORM BUILDER HERE
            // (object)array(
            //     'page' => 'test_form_builder',
            //     'view' => 'listing',
            //     'label' => 'Test Form Builder',
            //     'icon' => 'fa-edit',
            //     'url' => url('test_form_builder'),
            //     'show' => true,
            // ),
        ),
    ),
);