<?php

$this->siteMap = array(
    (object) [
        'group'         => 'Dashboard',
        'label'         => 'Dashboard',
        'icon'          => 'fa-dashboard',
        'url'           => url('dashboard'),
        'class'         => '',
        'show'          => true,
        'active_by'     => 'view',
    ],
    (object)array(
        'group'         => 'Jobs_listings',
        'page'          => 'jobs_listings',
        'label'         => lang('jobs_listings_heading'),
        'icon'          => 'fa-universal-access',
        'url'           => url('jobs_listings'),
        'class'         => 'Jobs_listings',
        'show'          => true,
        'show_heading'  => false,
        'active_by'     => 'view',
    ),
      (object)array(
        'group'         => 'Agency Staff',
        'page'          => 'agency_staff',
        'label'         => lang('agency_staff_heading'),
        'icon'          => 'fa-universal-access',
        'url'           => url('agency_staff'),
        'class'         => 'Agency_Staff',
        'show'          => true,
        'show_heading'  => false,
        'active_by'     => 'view',
    ),
    (object)array(
        'group'         => 'Recruiters',
        'page'          => 'recruiters',
        'label'         => lang('recruiters_heading'),
        'icon'          => 'fa-universal-access',
        'url'           => url('recruiters'),
        'class'         => 'Recruiters',
        'show'          => true,
        'show_heading'  => false,
        'active_by'     => 'view',
    ),
    (object) [
        'group'         => 'Candidates Management',
        'page'          => 'candidates',
        'label'         => lang('candidates_heading'),
        'icon'          => 'fa-users',
        'url'           => url('candidates'),
        'class'         => '',
        'show'          => true,
        'show_heading'  => true,
        'active_by'     => 'candidates',
        'items' => array(
            (object) [
                'page'          => 'candidates',
                'view'          => 'listing',
                'label'         => lang('candidates_heading'),
                'icon'          => 'fa-user-circle',
                'url'           => url('candidates'),
                'show'          => true,
            ],
        
        ),
    ],
);